### PR TITLE
MORE FLOODFILL!

### PR DESCRIPTION
**Pull request by null511**
- Added support for Amendments, Supplementaries, and Maccaws Lights mods.
- Added separate floodfill "tint saturation" slider.
- Turned off "iris <= 1.7.0" shadow fix since 1.7.1 is released.
- Add template readme and update script
- Update template line continuations to match current block.properties format.

### CODE REVIEW

**Comment by null511** [comment]
Looks like those block.properties changes ended up coming back around too, gonna have to reflect the changes you made into the template

**Comment by fayer3** [comment]
when you are at it you could also add the iris BLOCK_EMISSION_ATTRIBUTE feature, if not I already made the changes myself, based on the lightblock ids, could do that in a separate PR if needed https://github.com/fayer3/Bliss-Shader/commit/b001751de4dadc1970b1a928d4111c0a6cabb352

**Comment by X0nk** [comment]
o wait maybe i should have waited to merge that

**Comment by null511** [comment]
this should be done now

**Comment by X0nk** [comment]
alright, ill get merging

**Pull request merged**
